In [ ]:
import numpy as np

### Load basic data or numpy data

#### Load external data
`loadtxt` and `savetxt` : used to load data from a text file, with each row in the text file corresponding to a row in the array, and each value within that row being separated by a specified delimiter.

In [ ]:
data = np.loadtxt('file.txt', delimiter=',')
np.savetxt('file.txt', data, delimiter=',')

#### Load `.npy` files
`save` and `load`: used to save and load NumPy array data in a binary format with a `.npy` extension

In [ ]:
# To save an array to a binary file in NumPy `.npy` format
np.save('array.npy', data)

# To load an array from a `.npy` file
data = np.load('array.npy')

### Creating arrays with Numpy

#### Transform data to numpy array

In [ ]:
arr = np.array(data)

#### Set with specific values, e.g., `np.zeros`, `np.ones`, `np.full`, `np.eye`, `np.zeros_like`, `np.ones_like`

In [ ]:
# Create a 3x4 array filled with zeros (of float type by default)
arr_zeros = np.zeros((3, 4))

arr_zeros2 = np.zeros_like(arr_zeros)

# Create a 2x5 array filled with ones
arr_ones = np.ones((2, 5))

# Create a 4x4 array filled with a specific value, e.g., 9
arr_full = np.full((4, 4), 9)

# Create a 3x3 identity matrix
arr_identity = np.eye(3)

#### Set with range values, e.g., `np.arange`, `np.linspace`

In [ ]:
# Create a 1D array of numbers from 0 to 9
arr_range = np.arange(10)

# Create a 1D array of 5 numbers evenly spaced between 0 and 1
arr_linspace = np.linspace(0, 1, 5)  # [0.   0.25 0.5  0.75 1.  ]

#### Set with random values, e.g., `np.random.random`, `np.random.randint`

In [ ]:
# set random seed
np.random.seed(10)

# random sample with size in the interval [0.0, 1.0)
arr_random = np.random.random(size=(2,3))

# random sample with uniform distribution [0,1), similar to above
arr_random = np.random.random(2, 3)

# random integers
arr_random = np.random.randint(5)  # generate value in range [0,5)
arr_random = np.random.randint(5, high=6) # generate value in range [5,6)
arr_random = np.random.randint(0, high=6, size=(2,2))  # 

# random shuffle
np.random.shuffle(arr_random)

# random choice
colors = ['red', 'blue', 'green']
print(np.random.choice(colors))  # blue
print(repr(np.random.choice(colors, size=2)))  # ['blue', 'red']
# the probability is for different weights
print(repr(np.random.choice(colors, size=(2, 2), p=[0.8, 0.19, 0.01])))

#### Draw distributions, e.g., `np.random.uniform()`

In [ ]:
# uniform distribution
print(np.random.uniform())  # 0.31  # range [0,1)
print(np.random.uniform(low=-1.5, high=2.2))  # -0.618
print(repr(np.random.uniform(size=3))) 
print(repr(np.random.uniform(low=-3.4, high=5.9, size=(2, 2))))

# gaussian distribution
print(np.random.normal())  # default loc=0, scale=1
print(np.random.normal(loc=1.5, scale=3.5))
print(repr(np.random.normal(loc=-2.4, scale=4.0, size=(2, 2))))

#### Special values

In [ ]:
a = np.nan
b = np.inf
c = np.e
d = np.pi

### Handling NumPy Array

#### Check the array dimension with `shape` and `size`

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix.shape)  # (3,3)
print(matrix.size)  # 9  the total number of elements

#### Set the data type with `dtype` or `astype`

In [ ]:
arr = np.array(data, dtype=np.float32)

arr2 = arr.astype(np.float16)

#### Copy an array with `.copy()`

In [ ]:
a = np.array([0, 1])
b = a.copy()

#### Reshape data with `np.reshape`, `np.squeeze`, or `np.expand_dims`

In [ ]:
arr = np.arange(8)  # numbers from 0 to 7, shape is (8,)
arr2 = np.random.random(size=(2,3,1))

# reshape
reshaped_arr = np.reshape(arr, (2, 4)) # from (8,) to (2,4)

# squeeze
# axis: axes with size 1 to be removed, for this case only axis 2 can be removed
squeezed_arr = np.squeeze(arr2) # from (2,3,1) to (6,)
squeezed_arr2 = np.squeeze(arr2, axis=2) # from (2,3,1) to (2,3)

# expand_dims
expanded_arr = np.expand_dims(arr, axis=0) # add new axis at 0, new shape (1, 8)
expanded_arr2 = np.expand_dims(arr, axis=1) # add new axis at 1, new shape (8, 1)

#### Transpose data `np.transpose`

In [ ]:
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))  # shape [4,2]
transposed = np.transpose(arr)  # shape [2,4]

a = np.ones((1, 2, 3))
np.transpose(a, (1, 0, 2))  # shape (2,1,3)

#### Flatten data with `.flatten()`

In [ ]:
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))  # shape [4,2]
flattened = arr.flatten()  # shape: (8,)

#### Math Functions

In [ ]:
# exp
x = np.exp(arr)  # this will return e^arr

# log, log2, log10
y = np.log(arr)  # this will return log(arr)

# power
z = np.power(3, arr)  # this will return 3^arr

#### Matrix multiplication

In [ ]:
# When both inputs are 1-D, the output is the dot product.
arr1 = np.array([1, 2, 3])  # shape (1,3)
arr2 = np.array([-3, 0, 10])  # shape (1,3)
print(np.matmul(arr1, arr2))  # 27

# The dimensions must be valid for a matrix multiplication
arr3 = np.array([[1, 2], [3, 4], [5, 6]])  # shape (3,2)
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])  # shape (2,3)
print(repr(np.matmul(arr3, arr4)))  # shape (3,3)
print(repr(np.matmul(arr4, arr3)))  # shape (2,2)

#### Dot product with `np.dot()`

In [ ]:
vector_1 = np.array([1,2,3])
vector_2 = np.array([4,5,6])
dot_product = np.dot(vector_1,vector_2)

#### Indexing

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(repr(arr[:]))  # array([1, 2, 3, 4, 5])
print(repr(arr[1:]))  # [2,3,4,5]
print(repr(arr[2:4]))  # [3,4]
print(repr(arr[:-1]))  # [1,2,3,4]
print(repr(arr[-2:]))  # [4,5]

#### `argmin` and `argmax`

In [ ]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
print(np.argmin(arr[0]))  # 2
print(np.argmax(arr[2]))  # 1
print(np.argmin(arr))  # 5
print(repr(np.argmin(arr, axis=0)))  # [2,0,1]
print(repr(np.argmin(arr, axis=1)))  # [2,2,0]
print(repr(np.argmin(arr, axis=-1)))  # equal to last dimension, axis=1

#### Filtering data, use basic relation operations, e.g., `==`, `>`, etc., but we can also use `np.where`, `np.any`, and `np.all`

In [ ]:
arr = np.array([[0, 2, 3],
                [1, 3, -6],
                [-3, -2, 1]])
print(repr(arr == 3))

"""
array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])
"""

# more examples
print(repr(arr > 0))
print(repr(arr != 1))
# Negated from the previous step
print(repr(~(arr != 1)))

# verify isnan
arr = np.array([[0, 2, np.nan],
                [1, np.nan, -6],
                [np.nan, -2, 1]])
print(repr(np.isnan(arr)))

"""use np.where"""
# for single array
arr = np.array([0, 3, 5, 3, 1])
print(repr(np.where(arr == 3)))  # indices (array([1, 3]),)

# for 2-d array
arr = np.array([[0, 2, 3],
                [1, 0, 0],
                [-3, 0, 0]])
x_ind, y_ind = np.where(arr != 0)
print(repr(x_ind)) # x indices of non-zero elements array([0, 0, 1, 2])
print(repr(y_ind)) # y indices of non-zero elements array([1, 2, 0, 0])
print(repr(arr[x_ind, y_ind]))  # array([ 2,  3,  1, -3])

# this will assign true values in np_filter with positives and false with negatives
np.where(np_filter, positives, negatives)

"""np.any and np.all """
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])
print(np.any(arr > 0))  # True
print(np.all(arr > 0))  # False
print(repr(np.any(arr > 0, axis=0)))  # array([ True,  True,  True])
print(repr(np.any(arr > 0, axis=1)))  # array([False,  True,  True])
print(repr(np.all(arr > 0, axis=1)))  # array([False, False,  True])

#### Doing some basic statistics
- Calculate min and max
- Calculate mean, var, std, median

In [ ]:
# min and max
arr.min()
arr.max()
arr.min(axis=0)
arr.max(axis=-1)

# simple statistics
mean = np.mean(arr)
var = np.var(arr)
std = np.std(arr)
median = np.median(arr, axis=-1)

#### Aggregation
- Summation: `np.sum`, `np.cumsum`
- Concatenation: `np.concatenate` or `np.stack`

In [ ]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])

# ==========
# sum
np.sum(arr)
print(np.sum(arr, axis=0))  # [-2, 73, -53]

# ==========
# cumsum: return the cumulative sums for the lattened array
print(repr(np.cumsum(arr)))
print(repr(np.cumsum(arr, axis=0)))
print(repr(np.cumsum(arr, axis=1)))

"""
array([ 0, 72, 75, 76, 79, 19, 16, 14, 18])
array([[  0,  72,   3],
       [  1,  75, -57],
       [ -2,  73, -53]])
array([[  0,  72,  75],
       [  1,   4, -56],
       [ -3,  -5,  -1]])
"""

# ==========
# concatenation
arr1 = np.array([[0, 72, 3],
                 [1, 3, -60],
                 [-3, -2, 4]])
arr2 = np.array([[-15, 6, 1],
                 [8, 9, -4],
                 [5, -21, 18]])

print(repr(np.concatenate([arr1, arr2]).shape))  # 6, 3
print(repr(np.concatenate([arr1, arr2], axis=1).shape))  # 3, 6

# stack
# stacks two arrays along a new axis
print(repr(np.stack([arr1, arr2]).shape))  # 2, 3, 3
print(repr(np.stack([arr1, arr2], axis=1).shape))  # 3, 2, 3

#### Finding eigenvalues and eigenvectors

In [15]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
eigenvalues ,eigenvectors=np.linalg.eig(matrix)

# Calculate covariance function
cov = np.cov(matrix)